### ISSUE TITLE
FS-Meter on ESP32

### ISSUE THREAD

**Issue by tgrassmee** [jake-is-ESD-protected/ESP32FieldRecorder#1]
How did you implement the FS-Meter on the ESP32?  You use it for checking the audio waves right? 

Best regards

**Comment by jake-is-ESD-protected** [comment]
Hi,

please do **not** use this code for anything serious, it is very leaky and overall bad as it was my first C++ project.

I used it to visually detect clipping and to have something of a pseudo sound level meter, which of course is just an estimate as the mic's sensitivity is not included in the calculation.

You can implement an FS-meter like this:
```C
// assuming your audio has 16 bit
const double ref = 32767 * 32767; 

int8_t calcDBFS(int16_t* buf, uint32_t buf_len){
    uint32_t sum = 0;
    for(uint32_t i = 0; i < buf_len; i++){
        sum += buf[i] * buf[i];
    }
    return 10 * log10(sum / ref);
}
```
Please note that having audio with more bits causes this method to overflow. In that case, you need to divide by `ref` in the loop.

**Comment by tgrassmee** [comment]
No... its just for fun and learning purposes.... Thanks a lot....
